compressionLevel: 0

enableGlobalCache: true

nmMode: hardlinks-local # because other wise tsup.config.ts doesnt recognise the tsup import 🤷
nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.3.cjs
